Update to 1.21.4
TogAr2/MinestomPvP pull request #62
Opened 2024-12-23 14:30 UTC by CodeDoctorDE

Based on #61 but I couldn't test it currently

2024-12-26 02:53 UTC, lowercasebtw commented
yo uh, can u make this use consumable on sword items now instead of shield cuz shield is ahh

1.21.4+ now has third/first person animations for consumable block

https://github.com/kernitus/BukkitOldCombatMechanics/issues/769

2024-12-28 16:05 UTC, CodeDoctorDE commented
Hmm, yeah...
I need to find time working on it again..
I will see what I can do

2025-01-21 22:39 UTC, CodeDoctorDE commented
No, I'm currently struggeling getting the bow done, if you find a way, feel free to continue here

2025-01-22 00:58 UTC, lowercasebtw commented
Whats wrong with the bow?

2025-01-22 08:54 UTC, CodeDoctorDE commented
It doesn't shoot an arrow

2025-01-25 18:11 UTC, im-a-blobfish commented
is everything apart from the bow working correctly as far as you know?

2025-02-01 01:45 UTC, im-a-blobfish commented
@CodeDoctorDE 
Switching out PlayerUseItemEvent with PlayerCancelItemUseEvent in VanillaBowFeature seems to fix bow shooting

2025-03-04 18:36 UTC, TogAr2 requested changes
Most of it looks good to me! You can fix bows and tridents by using the item use cancel event instead. Also we need a way to handle food item consuming.

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/damage/DamageTypeInfo.java
> +		private static final long serialVersionUID = -1415972772651275647L;
Why exactly did you include this?

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/entity/projectile/ThrownEnderpearl.java
> +					Particle.PORTAL, false, true,
Should probably be false instead

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/explosion/VanillaExplosionSupplier.java
> +						player.sendPacket(new ExplosionPacket(new BlockVec(centerX, centerY, centerZ), knockbackVec, Particle.EXPLOSION, SoundEvent.ENTITY_GENERIC_EXPLODE));
Minor style comment, but this could use a newline

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					&& !(event.getItemStack().has(ItemComponent.FOOD) || event.getItemStack().has(ItemComponent.CONSUMABLE)))
I assume consumable would already include milk buckets, making the first check redundant?

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					&& !(event.getItemStack().has(ItemComponent.FOOD) || event.getItemStack().has(ItemComponent.CONSUMABLE)))
Does being consumable not also imply it is a food, making also the second check redundant?

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
>  		assert component != null;
This is no longer always the case

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					final Pos pos = player.getPosition();
There is already ChorusFruitUtil

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					if (potentials.isEmpty()) return; // TODO: do some fail over?
Should check MC source if they still do it, but I did add this in ChorusFruitUtil

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
Is there any alternative to this?

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/projectile/VanillaBowFeature.java
> +		node.addListener(PlayerUseItemEvent.class, event -> {
This should be the cancel item use event, as @im-a-blobfish stated

2025-03-04 18:36 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/projectile/VanillaTridentFeature.java
> +		node.addListener(PlayerFinishItemUseEvent.class, event -> {
Should again be the cancel event instead

2025-03-04 18:54 UTC, CodeDoctorDE commented
Thanks for the review. Most of these changes are from the previous pr so credit to it.
I will try to fix your comments

2025-03-04 19:40 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/entity/projectile/ThrownEnderpearl.java
> +					Particle.PORTAL, false, true,
added

2025-03-04 19:40 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/damage/DamageTypeInfo.java
> +		private static final long serialVersionUID = -1415972772651275647L;
from old pr, I removed it

2025-03-04 19:40 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
>  		assert component != null;
Added a check

2025-03-04 19:40 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					final Pos pos = player.getPosition();
added

2025-03-04 19:40 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					if (potentials.isEmpty()) return; // TODO: do some fail over?
added

2025-03-04 19:41 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
I don't know, this method is no longer in there, i need to check if there are alternatives

2025-03-04 19:41 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/projectile/VanillaBowFeature.java
> +		node.addListener(PlayerUseItemEvent.class, event -> {
added

2025-03-04 19:41 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/projectile/VanillaTridentFeature.java
> +		node.addListener(PlayerFinishItemUseEvent.class, event -> {
added

2025-03-04 19:43 UTC, CodeDoctorDE commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					&& !(event.getItemStack().has(ItemComponent.FOOD) || event.getItemStack().has(ItemComponent.CONSUMABLE)))
Hmm, sounds good, but I'm not sure with these new itemcomponents which can be added everywhere...

2025-03-04 20:52 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +					&& !(event.getItemStack().has(ItemComponent.FOOD) || event.getItemStack().has(ItemComponent.CONSUMABLE)))
Just checked and every food item also has a consumable component

2025-03-04 21:31 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
There doesn't seem to be, I wrote a method to get this manually since it doesn't have a lot of exceptions

2025-03-07 01:01 UTC, lowercasebtw commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
They replaced this with its own component afaik?

2025-03-07 01:03 UTC, lowercasebtw commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
![image](https://github.com/user-attachments/assets/fff04c0d-d807-4ce9-b260-57dc7e75dc46)

It comes from the "use_remainder" component

2025-03-11 01:14 UTC, lowercasebtw commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
Hope this gets noticed before the PR is accepted

2025-03-11 03:42 UTC, lowercasebtw commented
![image](https://github.com/user-attachments/assets/3b660e35-ccd0-4ffb-9c7f-82805e294711)

Whats the point of this

2025-03-11 12:13 UTC, TogAr2 commented
> Whats the point of this

Thanks for pointing that one out, it was still a remainder from previous code 😆

2025-03-11 12:14 UTC, TogAr2 commented on src/main/java/io/github/togar2/pvp/feature/food/VanillaFoodFeature.java
> +//		ItemStack leftOver = consumable.usingConvertsTo();
I see, thanks!

2025-03-11 12:14 UTC, CodeDoctorDE commented
Quick question: How does it work with the remainder component? Does minestom use the vanilla component as default?

2025-03-11 12:15 UTC, TogAr2 commented
Yes it does! In the item registry every remainder component from vanilla is predefined

2025-03-11 12:21 UTC, CodeDoctorDE commented
That sounds really cool! And you can remove the component if you want to have a bowl that don't have a remainder: https://javadoc.minestom.net/net/minestom/server/item/ItemStack.html#without(net.minestom.server.component.DataComponent)

2025-03-11 13:49 UTC, TogAr2 commented
Will have to wait for https://github.com/Minestom/Minestom/pull/2679, since right now spawning an arrow will cause a network error on the client

2025-03-18 12:20 UTC, lowercasebtw commented
Arrow meta or has been merged

2025-03-28 18:31 UTC, Andrei965 commented
Minestom merged the 1.21.4 branch

2025-03-28 19:18 UTC, merged